version: '3'
services:
  chrome:
    build: .
    container_name: cypress-chrome
    command: cypress run --browser chrome
    volumes:
      - ./cypress:/cypress
      - ./package.json:/package.json
      - ./cypress.config.js:/cypress.config.js

  electron:
    build: .
    container_name: cypress-container
    command: cypress run --headed
    volumes:
      - ./cypress:/cypress
      - ./package.json:/package.json
      - ./cypress.config.js:/cypress.config.js